# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVgz_5Axc1vliYhoHM6ksrf5XBmpobZk
"""

!pip install SpeechRecognition

import speech_recognition as sr
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

recognizer = sr.Recognizer()

with sr.AudioFile(file_name) as source:
    audio = recognizer.record(source)

    try:
        text = recognizer.recognize_google(audio)
        print("Recognized Text:")
        print(text)
    except sr.UnknownValueError:
        print("Could not understand the audio")
    except sr.RequestError as e:
        print("Error:", e)